apiVersion: v1
kind: Namespace
metadata:
  name: gitops-nlp-b
  labels:
    demo.microsoft.com/scenario: private-acr
    demo.microsoft.com/cluster: acr-auth-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-vision-b
  labels:
    demo.microsoft.com/scenario: private-acr
    demo.microsoft.com/cluster: acr-auth-demo