apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-model-trainer
  namespace: gitops-vision-a
  labels:
    app.kubernetes.io/name: vision-model-trainer
    demo.microsoft.com/scenario: private-acr-mapped
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vision-model-trainer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vision-model-trainer
        demo.microsoft.com/scenario: private-acr-mapped
    spec:
      containers:
        - name: trainer
          image: acrvisiontrainkgw7x.azurecr.io/model-trainer:v1
          imagePullPolicy: Always